# Generated by Django 5.2.1 on 2025-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
    ]
